import React, { useState, useEffect } from 'react';
import {
  ComposedChart, Line, Bar, Area, XAxis, YAxis,
  CartesianGrid, Tooltip, ResponsiveContainer, Cell
} from 'recharts';
import {
  Activity, TrendingUp, AlertTriangle, Info,
  BarChart2, Crosshair, ShieldAlert, Database
} from 'lucide-react';
import { cn } from './lib/utils';
import {
  VN100_STOCKS, generateMockData, generateSignals,
  StockData, ModelSignals, StockInfo
} from './lib/mockData';

// ─────────────────────────────────────────────────────────────────────────────
// Live data — generated by:
//   python run_pipeline.py
//   python data_inject.py
//
// If liveData.ts doesn't exist yet the try/catch keeps the app working with
// mock data until you run the pipeline.
// ─────────────────────────────────────────────────────────────────────────────

let LIVE_DATA: Record<string, { chartData: StockData[]; signals: ModelSignals }> = {};
let GENERATED_AT = '';

// ─────────────────────────────────────────────────────────────────────────────
// App
// ─────────────────────────────────────────────────────────────────────────────

export default function App() {
  const [selectedStock, setSelectedStock] = useState<StockInfo>(VN100_STOCKS[0]);
  const [chartData,     setChartData]     = useState<StockData[]>([]);
  const [signals,       setSignals]       = useState<ModelSignals | null>(null);
  
  const [hasLive, setHasLive] = useState(false);
  const [generatedAt, setGeneratedAt] = useState('');

  const [viewMode, setViewMode] = useState<'live'|'backtester'>('live');
  const [backtestData, setBacktestData] = useState<any>(null);

  useEffect(() => {
    fetch('http://localhost:3001/api/backtest')
      .then(res => res.json())
      .then(data => setBacktestData(data))
      .catch(err => console.warn('No backtest data:', err));
  }, []);

  useEffect(() => {
    fetch('http://localhost:3001/api/status')
      .then(res => res.json())
      .then(status => {
        if (status.ready) {
          setGeneratedAt(status.lastUpdated);
          return fetch('http://localhost:3001/api/data');
        }
        throw new Error('Pipeline not ready');
      })
      .then(res => res.json())
      .then(data => {
        LIVE_DATA = data;
        setHasLive(true);
      })
      .catch(err => {
        console.warn('Backend live data not ready, falling back to mock:', err.message);
      });
  }, []);

  useEffect(() => {
    const sym = selectedStock.symbol;
    if (hasLive && LIVE_DATA[sym]) {
      setChartData(LIVE_DATA[sym].chartData);
      setSignals(LIVE_DATA[sym].signals);
    } else {
      setChartData(generateMockData(sym));
      setSignals(generateSignals(sym));
    }
  }, [selectedStock, hasLive]);

  if (!signals) return null;

  const isLive = hasLive && Boolean(LIVE_DATA[selectedStock.symbol]);

  return (
    <div className="min-h-screen bg-[#050505] text-gray-100 font-sans selection:bg-blue-500/30">

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <header className="border-b border-gray-800 bg-[#0a0a0a] sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded bg-blue-600 flex items-center justify-center">
              <Activity className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="font-mono text-sm font-bold tracking-tight uppercase">
                VN100 Bound Predictor
              </h1>
              <p className="text-[10px] font-mono text-gray-500 uppercase tracking-widest">
                Institutional Quant Model
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
             <div className="flex bg-[#111] p-1 rounded-md border border-gray-800">
               <button 
                 onClick={() => setViewMode('live')} 
                 className={cn("px-3 py-1 text-xs font-mono rounded", viewMode === 'live' ? "bg-blue-600 text-white" : "text-gray-400 hover:text-gray-200")}
               >Live Dashboard</button>
               <button 
                 onClick={() => setViewMode('backtester')} 
                 className={cn("px-3 py-1 text-xs font-mono rounded", viewMode === 'backtester' ? "bg-purple-600 text-white" : "text-gray-400 hover:text-gray-200")}
               >Backtester</button>
             </div>

            {/* Data source badge */}
            <div className={cn(
              'flex items-center gap-1.5 px-2.5 py-1 rounded text-[10px] font-mono border',
              isLive
                ? 'bg-emerald-900/20 border-emerald-700/40 text-emerald-400'
                : 'bg-yellow-900/20  border-yellow-700/40  text-yellow-500'
            )}>
              <Database className="w-3 h-3" />
              {isLive
                ? `LIVE · ${new Date(generatedAt).toLocaleString()}`
                : 'MOCK · run pipeline + inject to get live data'}
            </div>

            {/* Ticker selector */}
            <div className="flex gap-2">
              {VN100_STOCKS.map(stock => (
                <button
                  key={stock.symbol}
                  onClick={() => setSelectedStock(stock)}
                  className={cn(
                    'px-3 py-1.5 text-xs font-mono rounded-md transition-colors border',
                    selectedStock.symbol === stock.symbol
                      ? 'bg-blue-900/30 border-blue-500/50 text-blue-400'
                      : 'bg-[#111] border-gray-800 text-gray-400 hover:bg-gray-800 hover:text-gray-200'
                  )}
                >
                  {stock.symbol}
                </button>
              ))}
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">

        {viewMode === 'live' ? (
          <>
            {/* ── Top Stats ──────────────────────────────────────────────────────── */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <StatCard
            title="Current Price"
            value={new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' })
              .format(selectedStock.price)}
            subValue={`${selectedStock.change > 0 ? '+' : ''}${selectedStock.changePercent}%`}
            trend={selectedStock.change >= 0 ? 'up' : 'down'}
          />
          <StatCard
            title="Market Regime (Hurst)"
            value={signals.hurst.toString()}
            subValue={signals.regime}
            trend={signals.hurst > 0.5 ? 'up' : 'down'}
            icon={<Activity className="w-4 h-4" />}
          />
          <StatCard
            title="VN-Index Trend Score"
            value={signals.vnIndexScore.toString()}
            subValue={signals.vnIndexScore > 0 ? 'Uptrend' : 'Downtrend'}
            trend={signals.vnIndexScore > 0 ? 'up' : 'down'}
            icon={<BarChart2 className="w-4 h-4" />}
          />
          <StatCard
            title="Sector RS"
            value={signals.sectorRS.toString()}
            subValue={`${selectedStock.sector} Sector`}
            trend={signals.sectorRS > 1 ? 'up' : 'down'}
            icon={<Crosshair className="w-4 h-4" />}
          />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* ── Charts ─────────────────────────────────────────────────────── */}
          <div className="lg:col-span-2 space-y-6">

            {/* Price & Bounds */}
            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-4">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-sm font-mono text-gray-400 uppercase tracking-wider">
                  Price & GARCH Bounds (T+3)
                </h2>
                <div className="flex gap-4 text-xs font-mono">
                  <span className="flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-blue-500 inline-block" /> Price
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-purple-500 inline-block" /> Kalman
                  </span>
                  <span className="flex items-center gap-1">
                    <span className="w-2 h-2 rounded-full bg-gray-600 inline-block" /> Bounds
                  </span>
                </div>
              </div>
              <div className="h-[400px] w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <ComposedChart data={chartData} margin={{ top:10, right:10, left:20, bottom:0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" vertical={false} />
                    <XAxis dataKey="date" stroke="#4b5563" fontSize={10} tickMargin={10} minTickGap={30} />
                    <YAxis domain={['auto','auto']} stroke="#4b5563" fontSize={10}
                      tickFormatter={v => (v/1000).toFixed(0)+'k'} />
                    <Tooltip content={<CustomTooltip />} />
                    <Area type="monotone" dataKey="upperBound" stroke="none" fill="#374151" fillOpacity={0.2} />
                    <Area type="monotone" dataKey="lowerBound" stroke="none" fill="#050505" fillOpacity={1} />
                    <Line type="monotone" dataKey="upperBound" stroke="#4b5563" strokeDasharray="3 3" dot={false} strokeWidth={1} />
                    <Line type="monotone" dataKey="lowerBound" stroke="#4b5563" strokeDasharray="3 3" dot={false} strokeWidth={1} />
                    <Line type="monotone" dataKey="kalman"     stroke="#a855f7" dot={false} strokeWidth={2} />
                    <Line type="monotone" dataKey="price"      stroke="#3b82f6" dot={false} strokeWidth={2} />
                  </ComposedChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Volume & Foreign Flow */}
            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-4">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-sm font-mono text-gray-400 uppercase tracking-wider">
                  Volume & Net Foreign Flow
                </h2>
              </div>
              <div className="h-[200px] w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <ComposedChart data={chartData} margin={{ top:10, right:10, left:20, bottom:0 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" vertical={false} />
                    <XAxis dataKey="date" stroke="#4b5563" fontSize={10} hide />
                    <YAxis yAxisId="left"  stroke="#4b5563" fontSize={10}
                      tickFormatter={v => (v/1e6).toFixed(1)+'M'} />
                    <YAxis yAxisId="right" orientation="right" stroke="#4b5563" fontSize={10}
                      tickFormatter={v => (v/1e6).toFixed(1)+'M'} />
                    <Tooltip
                      contentStyle={{ backgroundColor:'#111', borderColor:'#333', fontSize:'12px', fontFamily:'monospace' }}
                      itemStyle={{ color:'#fff' }}
                    />
                    <Bar yAxisId="left"  dataKey="volume" fill="#1f2937" />
                    <Bar yAxisId="right" dataKey="foreignFlow">
                      {chartData.map((_, i) => (
                        <Cell key={i} fill={chartData[i]?.foreignFlow > 0 ? '#10b981' : '#ef4444'} />
                      ))}
                    </Bar>
                  </ComposedChart>
                </ResponsiveContainer>
              </div>
            </div>
          </div>

          {/* ── Right Column ───────────────────────────────────────────────── */}
          <div className="space-y-6">

            {/* Execution Engine */}
            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl overflow-hidden">
              <div className="p-4 border-b border-gray-800 bg-[#111]">
                <h2 className="text-sm font-mono text-gray-400 uppercase tracking-wider flex items-center gap-2">
                  <ShieldAlert className="w-4 h-4" /> Execution Engine
                </h2>
              </div>
              <div className="p-5 space-y-6">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-gray-400">Action Signal</span>
                  <div className={cn(
                    'px-4 py-1.5 rounded font-mono font-bold text-sm',
                    signals.action === 'BUY'  ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' :
                    signals.action === 'SELL' ? 'bg-rose-500/20    text-rose-400    border border-rose-500/30'    :
                                                'bg-gray-800       text-gray-300    border border-gray-700'
                  )}>
                    {signals.action}
                  </div>
                </div>
                <div>
                  <span className="text-xs text-gray-500 uppercase font-mono block mb-1">Reasoning</span>
                  <p className="text-sm text-gray-300 bg-[#111] p-3 rounded border border-gray-800 font-mono leading-relaxed">
                    {signals.actionReason}
                  </p>
                </div>
                <div className="space-y-3 pt-4 border-t border-gray-800">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">Directional Probability</span>
                    <span className="text-sm font-mono text-blue-400">{signals.directionProb}%</span>
                  </div>
                  <div className="w-full bg-gray-800 rounded-full h-1.5">
                    <div className="bg-blue-500 h-1.5 rounded-full"
                      style={{ width:`${signals.directionProb}%` }} />
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <span className="text-sm text-gray-400">T+2.5 Drawdown Risk</span>
                    <span className={cn('text-sm font-mono',
                      signals.t25Risk > 30 ? 'text-rose-400' : 'text-emerald-400'
                    )}>
                      {signals.t25Risk}%
                    </span>
                  </div>
                  <div className="w-full bg-gray-800 rounded-full h-1.5">
                    <div className={cn('h-1.5 rounded-full',
                      signals.t25Risk > 30 ? 'bg-rose-500' : 'bg-emerald-500'
                    )}
                      style={{ width:`${Math.min(signals.t25Risk, 100)}%` }} />
                  </div>
                </div>
              </div>
            </div>

            {/* Alpha Features */}
            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl overflow-hidden">
              <div className="p-4 border-b border-gray-800 bg-[#111]">
                <h2 className="text-sm font-mono text-gray-400 uppercase tracking-wider flex items-center gap-2">
                  <Info className="w-4 h-4" /> Alpha Features
                </h2>
              </div>
              <div className="p-0">
                <FeatureRow label="GARCH(1,1) Volatility (σ)" value={`${signals.garchSigma}%`} />
                <FeatureRow label="VSA Ratio (Absorption)"    value={signals.vsaRatio.toString()} />
                <FeatureRow label="VWAP Deviation"
                  value={`${signals.vwapDeviation >= 0 ? '+' : ''}${signals.vwapDeviation}%`}
                  trend={signals.vwapDeviation > 0 ? 'up' : 'down'} />
                <FeatureRow label="Ceiling Demand"            value={signals.ceilingDemand.toString()} />
              </div>
            </div>

            {/* Vietnam Macro */}
            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl overflow-hidden">
              <div className="p-4 border-b border-gray-800 bg-[#111]">
                <h2 className="text-sm font-mono text-gray-400 uppercase tracking-wider flex items-center gap-2">
                  <TrendingUp className="w-4 h-4" /> Vietnam Macro
                </h2>
              </div>
              <div className="p-0">
                <FeatureRow label="USD/VND Trend (10d)"
                  value={`${signals.usdVndTrend >= 0 ? '+' : ''}${signals.usdVndTrend}%`}
                  trend={signals.usdVndTrend < 0 ? 'up' : 'down'} />
                <FeatureRow label="Interbank Overnight Rate"
                  value={`${signals.interbankRate}%`}
                  trend={signals.interbankRate < 3 ? 'up' : 'down'} />
              </div>
            </div>

            {/* Market Breadth */}
            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl overflow-hidden">
              <div className="p-4 border-b border-gray-800 bg-[#111]">
                <h2 className="text-sm font-mono text-gray-400 uppercase tracking-wider flex items-center gap-2">
                  <BarChart2 className="w-4 h-4" /> Market Breadth
                </h2>
              </div>
              <div className="p-0">
                <FeatureRow label="% Above 50-SMA"
                  value={`${signals.breadthPctAbove50Sma}%`}
                  trend={signals.breadthPctAbove50Sma > 50 ? 'up' : 'down'} />
                <FeatureRow label="A/D Ratio (10d MA)"
                  value={signals.adRatio10d.toString()}
                  trend={signals.adRatio10d > 1 ? 'up' : 'down'} />
              </div>
            </div>

            {/* Pattern Detection */}
            <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl overflow-hidden">
              <div className="p-4 border-b border-gray-800 bg-[#111]">
                <h2 className="text-sm font-mono text-gray-400 uppercase tracking-wider flex items-center gap-2">
                  <AlertTriangle className="w-4 h-4" /> Pattern Detection
                </h2>
              </div>
              <div className="p-0">
                <FeatureRow label="Bull Trap Flag"
                  value={signals.bullTrapFlag ? 'DETECTED' : 'CLEAR'}
                  trend={signals.bullTrapFlag ? 'down' : 'up'} />
                <FeatureRow label="Bear Trap Flag"
                  value={signals.bearTrapFlag ? 'DETECTED' : 'CLEAR'}
                  trend={signals.bearTrapFlag ? 'up' : 'down'} />
                <FeatureRow label="FOMO Signal"
                  value={signals.fomoSignal ? 'ACTIVE' : 'CLEAR'}
                  trend={signals.fomoSignal ? 'down' : 'up'} />
              </div>
            </div>

          </div>
        </div>
          </>
        ) : (
          <BacktestView selectedStock={selectedStock.symbol} backtestData={backtestData} />
        )}
      </main>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Sub-components
// ─────────────────────────────────────────────────────────────────────────────

function BacktestView({ selectedStock, backtestData }: { selectedStock: string, backtestData: any }) {
  if (!backtestData) {
    return <div className="text-gray-400 font-mono text-center p-10">Loading backtest data...</div>;
  }
  if (backtestData.error) {
    return <div className="text-rose-400 font-mono text-center p-10">{backtestData.error}</div>;
  }

  const statsList = backtestData.per_ticker || [];
  const stats = statsList.find((s:any) => s.ticker === selectedStock) || null;
  const trades = (backtestData.trades && backtestData.trades[selectedStock]) || [];
  const equity = (backtestData.equity && backtestData.equity[selectedStock]) || [];

  if (!stats) {
    return <div className="text-gray-400 font-mono text-center p-10">No backtest stats for {selectedStock}</div>;
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <StatCard title="Annual Return" value={`${(stats.ann_return * 100).toFixed(1)}%`} trend={stats.ann_return >= 0 ? 'up' : 'down'} />
        <StatCard title="Sharpe Ratio" value={stats.sharpe.toFixed(2)} trend={stats.sharpe >= 1 ? 'up' : 'down'} />
        <StatCard title="Win Rate" value={`${(stats.win_rate * 100).toFixed(1)}%`} />
        <StatCard title="Total Trades" value={stats.n_trades.toString()} />
      </div>

      <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-4">
        <h2 className="text-sm font-mono text-gray-400 uppercase mb-4">Capital Growth (Equity Curve)</h2>
        <div className="h-[400px] w-full">
          {equity.length > 0 ? (
            <ResponsiveContainer width="100%" height="100%">
              <ComposedChart data={equity} margin={{ top:10, right:10, left:20, bottom:0 }}>
                 <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" vertical={false} />
                 <XAxis dataKey="date" stroke="#4b5563" fontSize={10} tickMargin={10} minTickGap={30} />
                 <YAxis stroke="#4b5563" fontSize={10} domain={['auto', 'auto']} tickFormatter={v => (v/1e6).toFixed(0)+'M'} />
                 <Tooltip contentStyle={{ backgroundColor:'#111', borderColor:'#333', fontSize:'12px', fontFamily:'monospace' }} itemStyle={{ color:'#fff' }} />
                 <Area type="monotone" dataKey="equity" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={0.2} strokeWidth={2} />
              </ComposedChart>
            </ResponsiveContainer>
          ) : (
            <div className="flex items-center justify-center h-full text-gray-500 font-mono text-xs">No equity curve data available.</div>
          )}
        </div>
      </div>

      <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl overflow-hidden">
        <div className="p-4 border-b border-gray-800 bg-[#111]">
          <h2 className="text-sm font-mono text-gray-400 uppercase">Trade Ledger</h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-gray-400 font-mono">
            <thead className="bg-[#111] text-xs uppercase border-b border-gray-800">
              <tr>
                <th className="py-3 px-4">Entry Date</th>
                <th className="py-3 px-4">Exit Date</th>
                <th className="py-3 px-4">Entry Px</th>
                <th className="py-3 px-4">Exit Px</th>
                <th className="py-3 px-4">PnL %</th>
                <th className="py-3 px-4">Reason</th>
              </tr>
            </thead>
            <tbody>
              {trades.length === 0 && (
                <tr><td colSpan={6} className="py-8 text-center">No trades taken</td></tr>
              )}
              {trades.map((t: any, i: number) => (
                <tr key={i} className="border-b border-gray-800/50 hover:bg-gray-800/20">
                  <td className="py-2 px-4">{t.entry_date.substring(0, 10)}</td>
                  <td className="py-2 px-4">{t.exit_date.substring(0, 10)}</td>
                  <td className="py-2 px-4">{t.entry_price}</td>
                  <td className="py-2 px-4">{t.exit_price}</td>
                  <td className={cn("py-2 px-4", t.pnl_pct >= 0 ? "text-emerald-400" : "text-rose-400")}>{(t.pnl_pct * 100).toFixed(2)}%</td>
                  <td className="py-2 px-4 text-xs">{t.reason}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function StatCard({ title, value, subValue, trend, icon }: {
  title: string; value: string; subValue?: string; trend?: 'up'|'down'; icon?: React.ReactNode;
}) {
  return (
    <div className="bg-[#0a0a0a] border border-gray-800 rounded-xl p-4 flex flex-col justify-between">
      <div className="flex justify-between items-start mb-2">
        <span className="text-xs font-mono text-gray-500 uppercase tracking-wider">{title}</span>
        {icon && <span className="text-gray-600">{icon}</span>}
      </div>
      <div className="flex items-baseline gap-2">
        <span className="text-2xl font-light tracking-tight text-gray-100">{value}</span>
        {subValue && (
          <span className={cn('text-xs font-mono',
            trend === 'up' ? 'text-emerald-400' : trend === 'down' ? 'text-rose-400' : 'text-gray-500'
          )}>
            {subValue}
          </span>
        )}
      </div>
    </div>
  );
}

function FeatureRow({ label, value, trend }: {
  label: string; value: string; trend?: 'up'|'down';
}) {
  return (
    <div className="flex justify-between items-center p-4 border-b border-gray-800/50 last:border-0 hover:bg-gray-800/20 transition-colors">
      <span className="text-sm text-gray-400">{label}</span>
      <span className={cn('text-sm font-mono',
        trend === 'up' ? 'text-emerald-400' : trend === 'down' ? 'text-rose-400' : 'text-gray-200'
      )}>
        {value}
      </span>
    </div>
  );
}

const CustomTooltip = ({ active, payload, label }: any) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-[#111] border border-gray-800 p-3 rounded shadow-xl font-mono text-xs z-50">
      <p className="text-gray-400 mb-2">{label}</p>
      {payload.map((entry: any, i: number) => (
        <div key={i} className="flex justify-between gap-4 mb-1">
          <span style={{ color: entry.color }}>{entry.name}:</span>
          <span className="text-gray-200">{new Intl.NumberFormat('vi-VN').format(entry.value)}</span>
        </div>
      ))}
    </div>
  );
};
