/**
 * src/server.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Express API server that:
 *   GET /api/data              → serves public/ui_data.json (real pipeline output)
 *   GET /api/data/:ticker      → single-ticker slice
 *   POST /api/refresh          → triggers the Python pipeline (optional)
 *   GET  /                     → serves the built React app (production)
 *
 * Development: runs alongside `vite dev` on port 3001
 * Production:  serves the compiled /dist on port 3000
 *
 * Usage:
 *   npm run server          (dev — hot reload via tsx watch)
 *   npm run server:prod     (production)
 */

import express, { Request, Response } from "express";
import path from "path";
import fs from "fs";
import { execFile } from "child_process";

const app  = express();
const PORT = parseInt(process.env.PORT ?? "3001", 10);

// ── Path to the JSON generated by the Python pipeline ────────────────────────
const UI_DATA_PATH = path.resolve(process.cwd(), "public", "ui_data.json");
const PIPELINE_SCRIPT = path.resolve(process.cwd(), "script", "run.py");

// ─────────────────────────────────────────────────────────────────────────────
// Middleware
// ─────────────────────────────────────────────────────────────────────────────
app.use(express.json());

// CORS — allow Vite dev server (port 3000) to call this API
app.use((_req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin",  "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  next();
});

// ─────────────────────────────────────────────────────────────────────────────
// Helper — read & parse ui_data.json
// ─────────────────────────────────────────────────────────────────────────────
function readUiData(): Record<string, unknown> | null {
  if (!fs.existsSync(UI_DATA_PATH)) return null;
  try {
    const raw = fs.readFileSync(UI_DATA_PATH, "utf-8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Routes
// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET /api/data
 * Returns the full ui_data.json (all tickers).
 * Falls back gracefully with a 404 if the pipeline hasn't run yet.
 */
app.get("/api/data", (_req: Request, res: Response) => {
  const data = readUiData();
  if (!data) {
    return res.status(404).json({
      error: "ui_data.json not found",
      hint: "Run the Python pipeline first: python pipeline/pipeline.py",
    });
  }
  return res.json(data);
});

/**
 * GET /api/data/:ticker
 * Returns chart + signal data for a single ticker (e.g. /api/data/HPG).
 */
app.get("/api/data/:ticker", (req: Request, res: Response) => {
  const ticker = req.params.ticker.toUpperCase();
  const data = readUiData();
  if (!data) {
    return res.status(404).json({ error: "ui_data.json not found" });
  }
  const entry = data[ticker];
  if (!entry) {
    return res.status(404).json({
      error: `Ticker ${ticker} not found in ui_data.json`,
      available: Object.keys(data),
    });
  }
  return res.json(entry);
});

/**
 * POST /api/refresh
 * Triggers the Python pipeline in the background.
 * Body (optional): { "signalsOnly": true }  — uses --signals-only flag
 *
 * Returns immediately with 202 Accepted; poll /api/data when ready.
 */
app.post("/api/refresh", (req: Request, res: Response) => {
  const signalsOnly = Boolean(req.body?.signalsOnly);
  const args = signalsOnly
    ? ["inject.py", "--out", "../public/ui_data.json"]
    : ["run.py"];

  res.status(202).json({
    message: "Pipeline started",
    mode: signalsOnly ? "signals-only" : "full",
  });

  const scriptCwd = path.resolve(process.cwd(), "script");
  execFile("python", args, { cwd: scriptCwd }, (error, stdout, stderr) => {
    if (error) {
      console.error("[pipeline] error:", error.message);
      console.error(stderr);
    } else {
      console.log("[pipeline] finished:\n", stdout.slice(-500));
    }
  });
});

/**
 * GET /api/status
 * Returns the last-modified timestamp of ui_data.json (useful for polling).
 */
app.get("/api/status", (_req: Request, res: Response) => {
  if (!fs.existsSync(UI_DATA_PATH)) {
    return res.json({ ready: false, lastUpdated: null });
  }
  const stat = fs.statSync(UI_DATA_PATH);
  return res.json({
    ready:       true,
    lastUpdated: stat.mtime.toISOString(),
    tickers:     Object.keys(readUiData() ?? {}),
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Production — serve React build
// ─────────────────────────────────────────────────────────────────────────────

/**
 * GET /api/backtest
 * Returns the backtest_report.json generated by script/backtest.py.
 */
app.get("/api/backtest", (_req: Request, res: Response) => {
  const BACKTEST_PATH = path.resolve(process.cwd(), "script", "data", "reports", "backtest_report.json");
  if (!fs.existsSync(BACKTEST_PATH)) {
    return res.status(404).json({
      error: "backtest_report.json not found",
      hint: "Run the backtest first: python script/backtest.py",
    });
  }
  try {
    const raw = fs.readFileSync(BACKTEST_PATH, "utf-8");
    return res.json(JSON.parse(raw));
  } catch (err) {
    return res.status(500).json({ error: "Failed to parse backtest report" });
  }
});
const DIST = path.resolve(process.cwd(), "dist");
if (fs.existsSync(DIST)) {
  app.use(express.static(DIST));
  app.get("*", (_req, res) => res.sendFile(path.join(DIST, "index.html")));
}

// ─────────────────────────────────────────────────────────────────────────────
// Start
// ─────────────────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`\n  VN100 API server → http://localhost:${PORT}`);
  console.log(`  ui_data.json     → ${UI_DATA_PATH}`);
  console.log(`  Pipeline data    → ${fs.existsSync(UI_DATA_PATH) ? "✓ present" : "✗ missing (run pipeline first)"}`);
});

export default app;
